all:
	gcc -Wall -o bin/watch-dip watch-dip.c -lwiringPi
	gcc -Wall -o bin/watch-button watch-button.c -lwiringPi
	gcc -Wall -o bin/flash-leds flash-leds.c -lwiringPi
	gcc -Wall -o bin/print-dip print-dip.c -lwiringPi
	gcc -Wall -o bin/print-dip-table print-dip-table.c -lwiringPi
