all:
	gcc -Wall -o watch-dip watch-dip.c -lwiringPi
	gcc -Wall -o watch-button watch-button.c -lwiringPi
	gcc -Wall -o flash-leds flash-leds.c -lwiringPi
	gcc -Wall -o print-dip print-dip.c -lwiringPi
	gcc -Wall -o print-dip-table print-dip-table.c -lwiringPi